### PR TITLE
make the plugin card look more like the powercord plugin one

### PR DESCRIPTION
**Pull request by akisblack**

### CODE REVIEW

**Comment by LandenStephenss** [comment]
lol no

**Comment by akisblack** [comment]
tf? no explanation?

**Comment by ghost** [comment]
@LandenStephenss eggs plain

**Comment by xaiyadev** [comment]
> tf? no explanation?

I think becouse their dont like it. It is their plugin so they decide if they like that idea or not, and it sems like they dont like it

**Comment by ghost** [comment]
That's fair, but they should at least state why they feel like that's a bad change.

**Comment by xaiyadev** [comment]
> That's fair, but they should at least state why they feel like that's a bad change.

Feel the Same. Could make it a Bit respectfully.

**Comment by LandenStephenss** [comment]
> That's fair, but they should at least state why they feel like that's a bad change.

It wasn't the fact that it was a bad change, it was the fact that it had practically no information about what it did (other than the title), no description or screenshots. Didn't feel like cloning his fork just to test it, there is no reason to keep this thread going.

**Pull request closed without merging**
